### ISSUE TITLE
FR: Add IS_ISR() API to depict an ISR context.

### ISSUE THREAD

**Issue by pranjalchanda08** [VisorFolks/cyancore#101]
**Is your feature request related to a problem? Please describe.**
Add IS_ISR() API to depict an ISR context.

**Describe the solution you'd like**
An unified API to tell about current call context to help kernel being non-blocking if the kernel API is being called from ISR context.
 
```c
/**
  \brief   Get IPSR Register
  \details Returns the content of the IPSR Register.
  \return               IPSR Register value
 */
__STATIC_FORCEINLINE uint32_t __get_IPSR(void)
{
  uint32_t result;

  __ASM volatile ("MRS %0, ipsr" : "=r" (result) );
  return(result);
}
```
```c
#if    (__ARM_ARCH_7A__      == 1U)
/* CPSR mode bitmasks */
#define CPSR_MODE_USER            0x10U
#define CPSR_MODE_SYSTEM          0x1FU

#define IS_IRQ_MODE()             ((__get_mode() != CPSR_MODE_USER) && (__get_mode() != CPSR_MODE_SYSTEM))
#else
#define IS_IRQ_MODE()             (__get_IPSR() != 0U)
#endif

#define IS_IRQ()                  IS_IRQ_MODE()
```

**Comment by akashkollipara** [comment]
Added in_isr call in avr and riscv archs

**Comment by akashkollipara** [comment]
Note: Our framework shouldn't be aware of the exception layer. The idea of the exception will be decided by the programmer during compile time. Inspired from RISC-V arch.
