### ISSUE TITLE
FR: FreeRTOS implementation (Port to cyancore)

### ISSUE THREAD

**Issue by Shashank-Rangu** [VisorFolks/cyancore#102]
**Is your feature request related to a problem? Please describe.**
Cyancore currently does not have the required support for FreeRTOS

**Describe the solution you'd like**
FreeRTOS port onto Cyancore Framework

**Comment by akashkollipara** [comment]
@cr3a7ive-d3v can you please fill in the details of FR

**Comment by akashkollipara** [comment]
Closing this PR... will open a new one later.
