### ISSUE TITLE
<HELIOS> Anti Deadlock system

### ISSUE THREAD

**Issue by pranjalchanda08** [VisorFolks/cyancore#197]
**Is your feature request related to a problem? Please describe.**
The expectation is to detect and notify user about any thread not responding / deadlocked.

The Scheduler shall maintain a tick system logic to down-count a variable every single tick. 
The task is supposed to reset the ticks using a feed_api() and not let the timer ticks go down to absolute 0.

If the variable goes to 0 then it shall trigger a user callback to notify the thread in deadlock state and user can take a call to terminate the task if required. 

**OS Watchdog**

**Comment by akashkollipara** [comment]
`Pseudo OS Watchdog` --> Software/Virtual WDog.

**Comment by akashkollipara** [comment]
Alternatively... use hardware wdog to fire first IRQ to kill blocked task, blocked here refers to holding the resource for very long time or ends up waiting indefinitely for resource.

**Comment by pranjalchanda08** [comment]
We do not want to do that as many MCUs do not have HW Watchdog or the user may want to use the watchdog in any other way.

**Comment by pranjalchanda08** [comment]
Commits are merged. Hence closing the PR.
