### ISSUE TITLE
FR: Add RTT over JTAG feature

### ISSUE THREAD

**Issue by pranjalchanda08** [VisorFolks/cyancore#224]
**Is your feature request related to a problem? Please describe.**

Add support for logging over RTT protocol while using JTAG
Advantages:
 
1. Src code available from SEGGER
2. Can be used across the platforms
3. Truly highspeed than any other communications.

https://www.segger.com/products/debug-probes/j-link/technology/about-real-time-transfer/

Drawback:

1. In power save mode the terminal disconnects along with the JTAG connection.

**Comment by akashkollipara** [comment]
Closing this issue as "Won't Fix".
