### ISSUE TITLE
< DOC > Comment added in command box which makes user copy comment with the command

### ISSUE THREAD

**Issue by RahulGoyal-tech** [VisorFolks/cyancore#321]
**Describe the bug**
Comment is added in this box, due to which, while coyping command, comment also gets copied. Doesn't seem suitable, we should add this comment in next line.

![image](https://github.com/user-attachments/assets/6d7b386a-e696-4527-8f1f-2c80ecbb28e8)

**Expected behavior**
Only command should be copied and comment should be present in the next line for description purposes.

**Comment by akashkollipara** [comment]
`#` is a comment. It wont impact the execution.
Also, user should read the content and act, not just copy paste.

Closing this as it cannot be considered an issue.

**Comment by RahulGoyal-tech** [comment]
Alright Got It!
