### ISSUE TITLE
Build Support on Windows OS

### ISSUE THREAD

**Issue by akashkollipara** [VisorFolks/cyancore#42]
**Is your feature request related to a problem? Please describe.**
This feature is needed to build the cyancore software framework on Windows OS.
- As of now only Linux support is available but because of the paths, build fails even with windows supported toolchain.

**Describe the solution you'd like**
- N/A

**Describe alternatives you've considered**
- Use VSCode (Remote) with WSL enabled
- Use Ubuntu 20.04 Terminal
- Add VSCode plugin to support build and debug
- Bring in new build engine (!Last escort!)

**Comment by akashkollipara** [comment]
Raised on behalf of @gkunalupta

**Comment by pranjalchanda08** [comment]
We shall consider adding up extension of vs code to help people configure the build engine on cross platform setup.

**Comment by pranjalchanda08** [comment]
hi @akashkollipara, Lets discuss upon this task

**Comment by akashkollipara** [comment]
@gkunalupta please have a look at this

**Comment by akashkollipara** [comment]
Hey @pranjalchanda08,

I want to say this is a closed issue!
People who queried about running makefile on windows were aswered to use wsl shell and proceed.

**Comment by pranjalchanda08** [comment]
> Hey @pranjalchanda08,
> 
> I want to say this is a closed issue! People who queried about running makefile on windows were aswered to use wsl shell and proceed.

@akashkollipara,

That surely works as a workaround but on a longer run we need something that supports it on Win. I do remember we were discussing something on CDC to support this feature.

**Comment by akashkollipara** [comment]
> 

Yes, but i am re-evaluating the efforts behind it...

**Comment by pranjalchanda08** [comment]
Guess we can put it to lower priority.
