### ISSUE TITLE
FR: Add light weight multi-tasking kernel in Terravisor

### ISSUE THREAD

**Issue by akashkollipara** [VisorFolks/cyancore#49]
**Is your feature request related to a problem? Please describe.**
Terravisor needs multi-tasking support

**Describe the solution you'd like**
Create a mini kernel with various scheduling algorithms for multi tasking.

**Comment by akashkollipara** [comment]
@pranjalchanda08 
Please get started. This will be a shared issue. We need to keep the status updated.

**Comment by pranjalchanda08** [comment]
> @pranjalchanda08 Please get started. This will be a shared issue. We need to keep the status updated.

Sure

**Comment by pranjalchanda08** [comment]
Update: 
1. Task Functions are all updated.
2. Semaphore Functions are updated
3. Supports 2 scheduling algorithm currently

To Be done:
1. Scheduler algorithm needs to be done
2. Need to have a function to recognize if the wait call is from Task or ISR to prevent locking.
3. Power save mech to be done.
4. Testing is to be done

**Comment by pranjalchanda08** [comment]
Closing this issue with other open Items to the feature. Shall include them in Feature/Issue list in future.
