### ISSUE TITLE
FR: Add Syslog lib with Core dump

### ISSUE THREAD

**Issue by akashkollipara** [VisorFolks/cyancore#6]
for starters A basic debug feature to dump the reg frame on interrupt or error...

**Comment by pranjalchanda08** [comment]
@akashkollipara,

Are we looking for a trace-back feature on panics?

**Comment by akashkollipara** [comment]
Having trace will be a good feature. But we are constrained with RAM size on lower mcu archs.

For now we shall have simple register snapshot to be printed.

**Comment by pranjalchanda08** [comment]
But we need to be specific of what memory regions we want to print as part of dump. Since the memory map would differ Arch-Arch.

**Comment by akashkollipara** [comment]
> 
> 
> But we need to be specific of what memory regions we want to print as part of dump. Since the memory map would differ Arch-Arch.

So that why we shall place such drivers in arch or plat/arch folders with _WEAK dummy functions implemented.

**Comment by akashkollipara** [comment]
Updating title!
Renaming it to Core Dump for AVR and RISC-V and Syslog update

**Comment by akashkollipara** [comment]
Taking this on priority!

**Comment by akashkollipara** [comment]
Marking this as closed...
